import { Nunito_Sans } from 'next/font/google';
import Link from 'next/link';
import ThemeInput from './components/ThemeInput';
import './globals.css';

const nunitoSans = Nunito_Sans({
  weight: ['300', '400', '600', '800'],
  subsets: ['latin'],
  variable: '--ff-nunito-sans',
});

export const metadata = {
  title: 'Where in the world?',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html
      lang="en"
      className={`h-full ${nunitoSans.variable}`}
      suppressHydrationWarning
    >
      <body className="h-full">
        <script
          dangerouslySetInnerHTML={{
            __html: `const storedTheme=localStorage.getItem('theme');'dark'===storedTheme&&document.documentElement.setAttribute('data-theme','dark');`,
          }}
        />
        <div id="app-root" className="min-h-full">
          <header className="bg-bg-secondary">
            <div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-6">
              <Link
                href="/"
                className="text-sm font-extrabold lg:text-2xl"
                aria-label="Home"
              >
                Where in the world?
              </Link>

              <label className="cursor-pointer p-2 pr-0">
                <ThemeInput />
                <span
                  className="flex items-center gap-2 text-xs font-semibold capitalize lg:text-base"
                  aria-hidden
                >
                  <svg
                    className="w-4"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                  >
                    <path
                      className="fill-text-primary"
                      d="M10 7C10 10.866 13.134 14 17 14C18.9584 14 20.729 13.1957 21.9995 11.8995C22 11.933 22 11.9665 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2C12.0335 2 12.067 2 12.1005 2.00049C10.8043 3.27098 10 5.04157 10 7ZM4 12C4 16.4183 7.58172 20 12 20C15.0583 20 17.7158 18.2839 19.062 15.7621C18.3945 15.9187 17.7035 16 17 16C12.0294 16 8 11.9706 8 7C8 6.29648 8.08133 5.60547 8.2379 4.938C5.71611 6.28423 4 8.9417 4 12Z"
                    />
                  </svg>
                  Dark mode
                </span>
              </label>
            </div>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
